"""add_learn_module_tables

Revision ID: 2205752520a7
Revises: 
Create Date: 2026-05-26 08:12:53.634372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2205752520a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_scenario_categories_course_id'), 'scenario_categories', ['course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_categories_course_id'), table_name='scenario_categories')
    # ### end Alembic commands ###
