"""add_translations_jsonb

Revision ID: f6c0285accf1
Revises: 2205752520a7
Create Date: 2026-05-26 09:35:24.020933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6c0285accf1'
down_revision: Union[str, None] = '2205752520a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('domains', sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('lessons', sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('quiz_questions', sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('quizzes', sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scenario_categories', sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scenarios', sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'translations')
    op.drop_column('scenario_categories', 'translations')
    op.drop_column('quizzes', 'translations')
    op.drop_column('quiz_questions', 'translations')
    op.drop_column('lessons', 'translations')
    op.drop_column('domains', 'translations')
    op.drop_column('courses', 'translations')
    # ### end Alembic commands ###
